/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-10-19 19:02:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class processaLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <title>Transferência de Dinheiro</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("          rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("          crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("            integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("            crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            height: 80vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-mastercard {\r\n");
      out.write("		    width: 300px;\r\n");
      out.write("		    background-color: #ffcc00;\r\n");
      out.write("		    border: 1px solid #000;\r\n");
      out.write("		    padding: 10px;\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		    box-shadow: 5px 5px 5px #888888;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.card-logo img {\r\n");
      out.write("		    max-width: 60px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.card-number {\r\n");
      out.write("		    font-size: 18px;\r\n");
      out.write("		    margin-top: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.card-holder {\r\n");
      out.write("		    font-size: 14px;\r\n");
      out.write("		    margin-top: 10px;\r\n");
      out.write("		}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    // Dados do usuário
    String nome = "Vitor Hugo";
    double saldo = 100.0;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"col-lg-12\">\r\n");
      out.write("        <h1 class=\"mb-3\">Bem-vindo, ");
      out.print(nome );
      out.write("!</h1>\r\n");
      out.write("        <p>Saldo: R$ <span id=\"saldo\">");
      out.print(String.format("%.2f", saldo) );
      out.write("</span></p>\r\n");
      out.write("\r\n");
      out.write("        <!-- Formulário de transferência -->\r\n");
      out.write("        <form id=\"transferForm\" action=\"Transferencia.jsp\" method=\"post\">\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"destinatario\" class=\"form-label\">Destinatário:</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"destinatario\" name=\"destinatario\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"valor\" class=\"form-label\">Valor (R$):</label>\r\n");
      out.write("                <input type=\"number\" class=\"form-control\" id=\"valor\" name=\"valor\" step=\"0.01\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"hidden\" name=\"saldoAtual\" value=\"");
      out.print( saldo );
      out.write("\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" id=\"transferirBtn\">Transferir</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"alert alert-danger mt-3\" id=\"error-message\" style=\"display: none;\"></div>\r\n");
      out.write("    </div><br>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#cartaoModal\">\r\n");
      out.write("    	Meu Cartão\r\n");
      out.write("	</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"cartaoModal\" tabindex=\"-1\" aria-labelledby=\"cartaoModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"cartaoModalLabel\">FIVEBANK</h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Fechar\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"card-mastercard\">\r\n");
      out.write("                    <div class=\"card-logo\">\r\n");
      out.write("                        <img src=\"./img/mastercard-logo.png\" alt=\"Mastercard\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-info\">\r\n");
      out.write("                        <p class=\"card-number\">**** **** **** 1234</p>\r\n");
      out.write("                        <p class=\"card-holder\">Titular: ");
      out.print(nome );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Fechar</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById(\"transferirBtn\").addEventListener(\"click\", function () {\r\n");
      out.write("        var destinatario = document.getElementById(\"destinatario\").value;\r\n");
      out.write("        var valor = parseFloat(document.getElementById(\"valor\").value);\r\n");
      out.write("        var saldoAtual = ");
      out.print( saldo );
      out.write(";\r\n");
      out.write("\r\n");
      out.write("        if (!destinatario.trim()) {\r\n");
      out.write("            showError(\"Por favor, insira um destinatário.\");\r\n");
      out.write("        } else if (isNaN(valor) || valor <= 0) {\r\n");
      out.write("            showError(\"Por favor, insira um valor válido maior que zero.\");\r\n");
      out.write("        } else if (valor > saldoAtual) {\r\n");
      out.write("            showError(\"Saldo insuficiente para realizar a transferência.\");\r\n");
      out.write("        } else {\r\n");
      out.write("            document.forms[\"transferForm\"].submit();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function showError(message) {\r\n");
      out.write("        document.getElementById(\"error-message\").innerText = message;\r\n");
      out.write("        document.getElementById(\"error-message\").style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
