/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-10-19 18:47:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class site_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>FiveBank</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Inclua as bibliotecas do Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Estilos personalizados -->\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #fff; /* Fundo branco */\r\n");
      out.write("            color: #000; /* Texto preto */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: #fff; /* Navbar de fundo branco */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            color: #ffd700; /* Cor do texto do navbar em dourado */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .jumbotron {\r\n");
      out.write("            background: url('./img/background.jpg') no-repeat center center; /* Imagem de fundo da seção de boas-vindas */\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            color: #000; /* Cor do texto na seção de boas-vindas (preto) */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bank-card {\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("            background-color: #fff; /* Fundo branco nos cards */\r\n");
      out.write("            color: #000; /* Texto preto nos cards */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bank-card h5 {\r\n");
      out.write("            color: #ffd700; /* Cor do título em dourado nos cards */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background-color: #ffd700; /* Botão em dourado */\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: #ffd700; /* Navbar com background dourado */\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            color: #000; /* Cor do texto do navbar em preto */\r\n");
      out.write("            font-size: 24px; /* Tamanho da fonte do título */\r\n");
      out.write("            font-weight: bold; /* Estilo de fonte em negrito */\r\n");
      out.write("        }\r\n");
      out.write("        .navbar .btn-cadastro {\r\n");
      out.write("            background-color: #ffd700; /* Botão em dourado */\r\n");
      out.write("            color: #000; /* Cor do texto do botão em preto */\r\n");
      out.write("            margin-right: 10px; /* Margem à direita para espaçamento */\r\n");
      out.write("        }\r\n");
      out.write("        .navbar .btn-cadastro:hover {\r\n");
      out.write("            background-color: #ffd700; /* Cor de destaque do botão */\r\n");
      out.write("            color: #000; /* Cor do texto do botão em preto */\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">FiveBank</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <h2>Bem-vindo ao FiveBank</h2>\r\n");
      out.write("            <p>Somos o seu banco de confiança, oferecendo soluções financeiras de última geração.</p>\r\n");
      out.write("            <p>Confira nossos serviços e descubra como podemos ajudá-lo a alcançar seus objetivos financeiros.</p>\r\n");
      out.write("            <a href=\"cadastro.jsp\" class=\"btn btn-primary\">Comece Agora</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <img src=\"./img/2logo.png\" alt=\"Tech5 Bank Logo\" class=\"img-fluid\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div><br><br>\r\n");
      out.write("\r\n");
      out.write("    <!-- Seção Missão, Visão e Valores com Cards -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Missão -->\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"card bank-card\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"card-title\">Missão</h5>\r\n");
      out.write("                        <p class=\"card-text\">A nossa missão é fornecer soluções financeiras inovadoras, acessíveis e seguras ao cliente, capacitando-os a atingir seus objetivos financeiros com facilidade. Buscamos transformar a experiência financeira por meio da tecnologia, focando na satisfação do cliente e na inclusão financeira, ao mesmo tempo que promovemos a transparência e a responsabilidade social.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Visão -->\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"card bank-card\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"card-title\">Visão</h5>\r\n");
      out.write("                        <p class=\"card-text\">O Five Bank tem a visão de se tornar líder global em inovação e serviços financeiros digitais, redefinindo o cenário financeiro e tecnológico. Nós buscamos capacitar pessoas e empresas em todo o mundo, oferecendo uma experiência financeira descomplicada, moldada às necessidades de clientes que compartilham valores comuns.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Valores -->\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"card bank-card\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"card-title\">Valores</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>Tecnologia Inovadora</li>\r\n");
      out.write("                            <li>Sistema Simples</li>\r\n");
      out.write("                            <li>Acessibilidade</li>\r\n");
      out.write("                            <li>Responsabilidade Financeira</li>\r\n");
      out.write("                            <li>Excelência no Atendimento</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
